flink:
  kafkaSource:
    topic: your_topic_name
    bootstrapServers: your_kafka_broker:9092
    format: json
    startupMode: earliest-offset
  dorisSink:
    fenodes: your_doris_fe_host:8030
    tableIdentifier: your_db.your_table
    username: your_username
    password: your_password
    labelPrefix: your_label_prefix
    properties:
      format: json
      strip_outer_array: true
